// @vitest-environment node
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";

const mocks = vi.hoisted(() => ({
  authenticatePilot: vi.fn(),
  validateProcessedJpeg: vi.fn(),
  putPrivateEvidence: vi.fn(),
  deletePrivateEvidence: vi.fn(),
  evidenceCreate: vi.fn(),
}));

vi.mock("@/server/auth", () => ({
  assertCsrf: vi.fn().mockResolvedValue(undefined),
  authenticatePilot: mocks.authenticatePilot,
}));
vi.mock("@/server/storage", () => ({
  MAX_EVIDENCE_BYTES: 10 * 1024 * 1024,
  deletePrivateEvidence: mocks.deletePrivateEvidence,
  putPrivateEvidence: mocks.putPrivateEvidence,
  validateProcessedJpeg: mocks.validateProcessedJpeg,
}));
vi.mock("@/server/prisma", () => ({
  getPrisma: () => ({ evidenceImage: { create: mocks.evidenceCreate } }),
}));

import { POST } from "@/app/api/evidence-images/route";
import { resetServerConfigForTests } from "@/server/config";

function request(body?: BodyInit, contentType?: string) {
  return new NextRequest("http://127.0.0.1:3000/api/evidence-images", {
    method: "POST",
    headers: {
      origin: "http://127.0.0.1:3000",
      "x-request-id": "image-request",
      ...(contentType ? { "content-type": contentType } : {}),
    },
    body,
  });
}

describe("evidence image upload route", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.stubEnv("APP_ORIGIN", "http://127.0.0.1:3000");
    resetServerConfigForTests();
    mocks.authenticatePilot.mockResolvedValue({
      id: "pilot-1",
      personId: "person-1",
      csrfToken: "csrf",
    });
  });

  afterEach(() => {
    vi.unstubAllEnvs();
    resetServerConfigForTests();
  });

  it("returns a structured 422 when the multipart file is missing", async () => {
    const response = await POST(request());

    expect(response.status).toBe(422);
    await expect(response.json()).resolves.toMatchObject({
      error: { code: "INVALID_IMAGE", requestId: "image-request" },
    });
    expect(mocks.validateProcessedJpeg).not.toHaveBeenCalled();
    expect(mocks.putPrivateEvidence).not.toHaveBeenCalled();
    expect(mocks.evidenceCreate).not.toHaveBeenCalled();
  });

  it("rejects non-JPEG uploads before storage or database writes", async () => {
    const boundary = "----crewqual-test-boundary";
    const body = [
      `--${boundary}`,
      'Content-Disposition: form-data; name="file"; filename="evidence.png"',
      "Content-Type: image/png",
      "",
      "png",
      `--${boundary}--`,
      "",
    ].join("\r\n");

    const response = await POST(request(body, `multipart/form-data; boundary=${boundary}`));

    expect(response.status).toBe(422);
    await expect(response.json()).resolves.toMatchObject({
      error: { code: "INVALID_IMAGE", requestId: "image-request" },
    });
    expect(mocks.validateProcessedJpeg).not.toHaveBeenCalled();
    expect(mocks.putPrivateEvidence).not.toHaveBeenCalled();
    expect(mocks.evidenceCreate).not.toHaveBeenCalled();
  });

  it("persists only regenerated bytes and marks the database source version", async () => {
    const regenerated = new Uint8Array([0xff, 0xd8, 1, 0xff, 0xd9]);
    mocks.validateProcessedJpeg.mockResolvedValue({
      width: 20,
      height: 10,
      byteSize: 3,
      sha256: "original-digest",
      storageBytes: regenerated,
      storageByteSize: regenerated.length,
      storageSha256: "regenerated-digest",
    });
    mocks.putPrivateEvidence.mockResolvedValue("evidence/new.jpg");
    mocks.evidenceCreate.mockImplementation(({ data }) => ({ id: "image-1", ...data }));
    const form = new FormData();
    form.append(
      "file",
      new File([new Uint8Array([1, 2, 3])], "evidence.jpg", { type: "image/jpeg" }),
    );
    const uploadRequest = request();
    vi.spyOn(uploadRequest, "formData").mockResolvedValue(form);
    const response = await POST(uploadRequest);
    expect(response.status).toBe(201);
    expect(mocks.putPrivateEvidence).toHaveBeenCalledWith(regenerated, "regenerated-digest");
    expect(mocks.evidenceCreate).toHaveBeenCalledWith({
      data: expect.objectContaining({
        personId: "person-1",
        storageEncodingVersion: 1,
        sanitizedAt: expect.any(Date),
        byteSize: regenerated.length,
        sha256: "regenerated-digest",
      }),
    });
  });
});
